### ISSUE TITLE
parameters select

### ISSUE THREAD

**Issue by codeseeking** [gionuno/local_tangent_space_alignment#1]
hello, thanks your effort, I want to know how to select the d of parameters in the ltsa?

**Comment by gionuno** [comment]
Sorry, I haven't logged in for a while. The d is selected based on what you need. Check out main.m for examples.

**Comment by codeseeking** [comment]
I see, but if the performance is not good. How can I select it? Whether it is determinded by cross validation?

**Comment by gionuno** [comment]
it really depends on what you want to do... yes, i guess you could try cross-validation to find an appropriate d. I didn't try it, the examples given are better seen visually.

**Comment by codeseeking** [comment]
Thank you for your answer, what my task is to classificate, so the parameter d is critical for my classification performance.


| |
杨定康
|
|
邮箱：18381303772@163.com
|

签名由 网易邮箱大师 定制

On 12/19/2018 08:57, Giovanni Nuño wrote:

it really depends on what you want to do... yes, i guess you could try cross-validation to find an appropriate d. I didn't try it, the examples given are better seen visually.

**Comment by gionuno** [comment]
cross validation seems like a reasonable choice to find an a good d. Once you use LTSA on your points of interest, you plug in the t-vectors (the result) into a classifier.

**Comment by codeseeking** [comment]
I can't understand the last statement, would you like to describe it more details, thanks very much.


| |
杨定康
|
|
邮箱：18381303772@163.com
|

签名由 网易邮箱大师 定制

On 12/20/2018 01:54, Giovanni Nuño wrote:

cross validation seems like a reasonable choice to find an a good d. Once you use LTSA on your points of interest, you plug in the t-vectors (the result) into a classifier.

**Comment by gionuno** [comment]
Have you read the paper? LTSA is a nonlinear dimensional reduction that uses k-nearest neighbours to create a special sort of graph... onto which an eigenvector solver is then applied to find d vectors, let's say T is the matrix, each row of T (T(i,:)) is a t-vector.

**Comment by codeseeking** [comment]
Yes, I have watched this paper, the parameter d is difficult to be chosen, so I think cross validation is a good idea.


| |
杨定康
|
|
邮箱：18381303772@163.com
|

签名由 网易邮箱大师 定制

On 12/21/2018 01:50, Giovanni Nuño wrote:

Have you read the paper? LTSA is a nonlinear dimensional reduction that uses k-nearest neighbours to create a special sort of graph... onto which an eigenvector solver is then applied to find d vectors, let's say T is the matrix, each row of T (T(i,:)) is a t-vector.
